package emotionalsongs;

import javax.swing.*;
import java.awt.*;
import java.text.Format;
import java.text.NumberFormat;

public class MainView extends JFrame
{
	private MainController mc;
	JPanel MainPanel;
	JButton ricercaButton;
	JButton visualizzaEmozioniButton;
	JPanel ButtonPanel;
	JButton logOutButton;
	JList SongList;
	JTextField SearchField;
	JFormattedTextField annoField;
	JRadioButton titoloRadioButton;
	JRadioButton autoreRadioButton;
	JRadioButton autoreEAnnoRadioButton;
	JButton inserisciEmozioneButton;
	JButton accediButton;
	JPanel SearchPanel;
	JPanel ListPanel;
	ButtonGroup buttonGroup;
	
	public MainView()
	{
		super("EmotionalSong");
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		buttonGroup = new ButtonGroup();
		buttonGroup.add(titoloRadioButton);
		buttonGroup.add(autoreRadioButton);
		buttonGroup.add(autoreEAnnoRadioButton);
		titoloRadioButton.setSelected(true);
		annoField = new JFormattedTextField(NumberFormat.getNumberInstance());
		annoField.setColumns(5);
		
		mc = new MainController(this); //TODO controlla interazione tra le 3 classi dal main
		accediButton.addActionListener(mc);
		ricercaButton.addActionListener(mc);
		visualizzaEmozioniButton.addActionListener(mc);
		logOutButton.addActionListener(mc);
		inserisciEmozioneButton.addActionListener(mc);
		titoloRadioButton.addActionListener(mc);
		autoreRadioButton.addActionListener(mc);
		autoreEAnnoRadioButton.addActionListener(mc);
		
	}
	
	public void setLoggedIn()
	{
		accediButton.setVisible(false);
		logOutButton.setVisible(true);
		update(ButtonPanel);
	}
	
	public void setLoggedOut()
	{
		logOutButton.setVisible(false);
		accediButton.setVisible(true);
		update(ButtonPanel);
	}
	
	public void setDoubleBar()
	{
		SearchField.setColumns(15);
		annoField.setColumns(5);
		annoField.setVisible(true);
		update(SearchPanel);
	}
	
	public void setMonoBar()
	{
		SearchField.setColumns(25);
		annoField.setVisible(false);
		annoField.setText("");
		update(SearchPanel);
	}
	
	private void update(JPanel panel)
	{
		panel.validate();
		panel.repaint();
	}
	
	{
		// GUI initializer generated by IntelliJ IDEA GUI Designer
		// >>> IMPORTANT!! <<<
		// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}
	
	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$()
	{
		MainPanel = new JPanel();
		MainPanel.setLayout(new BorderLayout(0, 0));
		ListPanel = new JPanel();
		ListPanel.setLayout(new BorderLayout(0, 0));
		MainPanel.add(ListPanel, BorderLayout.CENTER);
		final JScrollPane scrollPane1 = new JScrollPane();
		scrollPane1.setPreferredSize(new Dimension(300, 200));
		ListPanel.add(scrollPane1, BorderLayout.CENTER);
		SongList = new JList();
		final DefaultListModel defaultListModel1 = new DefaultListModel();
		SongList.setModel(defaultListModel1);
		scrollPane1.setViewportView(SongList);
		ButtonPanel = new JPanel();
		ButtonPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
		MainPanel.add(ButtonPanel, BorderLayout.SOUTH);
		accediButton = new JButton();
		accediButton.setText("Accedi");
		ButtonPanel.add(accediButton);
		ricercaButton = new JButton();
		ricercaButton.setText("Ricerca");
		ButtonPanel.add(ricercaButton);
		visualizzaEmozioniButton = new JButton();
		visualizzaEmozioniButton.setText("Visualizza Emozioni");
		ButtonPanel.add(visualizzaEmozioniButton);
		logOutButton = new JButton();
		logOutButton.setEnabled(true);
		logOutButton.setText("Log Out");
		logOutButton.setVisible(false);
		ButtonPanel.add(logOutButton);
		inserisciEmozioneButton = new JButton();
		inserisciEmozioneButton.setText("Inserisci Emozione");
		inserisciEmozioneButton.setVisible(false);
		ButtonPanel.add(inserisciEmozioneButton);
		SearchPanel = new JPanel();
		SearchPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
		MainPanel.add(SearchPanel, BorderLayout.NORTH);
		SearchField = new JTextField();
		SearchField.setColumns(25);
		SearchField.setMinimumSize(new Dimension(100, 30));
		SearchField.setPreferredSize(new Dimension(256, 30));
		SearchField.setText("");
		SearchPanel.add(SearchField);
		annoField.setMinimumSize(new Dimension(50, 30));
		annoField.setPreferredSize(new Dimension(50, 30));
		annoField.setVisible(false);
		SearchPanel.add(annoField);
		final JLabel label1 = new JLabel();
		label1.setText("Ricerca per:");
		SearchPanel.add(label1);
		titoloRadioButton = new JRadioButton();
		titoloRadioButton.setText("Titolo");
		SearchPanel.add(titoloRadioButton);
		autoreRadioButton = new JRadioButton();
		autoreRadioButton.setText("Autore");
		SearchPanel.add(autoreRadioButton);
		autoreEAnnoRadioButton = new JRadioButton();
		autoreEAnnoRadioButton.setText("Autore e Anno");
		SearchPanel.add(autoreEAnnoRadioButton);
	}
	
	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$()
	{
		return MainPanel;
	}
	
}
